// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: olympus/analytic/v1/analytic.proto

package analyticv1connect

import (
	v1 "OlympusGCP-Data-AI/40000-Communication-Contracts/430-Protocol-Definitions/000-gen/analytic/v1"
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// AnalyticServiceName is the fully-qualified name of the AnalyticService service.
	AnalyticServiceName = "olympus.analytic.v1.AnalyticService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// AnalyticServiceGetDownloadURLProcedure is the fully-qualified name of the AnalyticService's
	// GetDownloadURL RPC.
	AnalyticServiceGetDownloadURLProcedure = "/olympus.analytic.v1.AnalyticService/GetDownloadURL"
	// AnalyticServiceUploadObjectProcedure is the fully-qualified name of the AnalyticService's
	// UploadObject RPC.
	AnalyticServiceUploadObjectProcedure = "/olympus.analytic.v1.AnalyticService/UploadObject"
	// AnalyticServiceUpsertProcedure is the fully-qualified name of the AnalyticService's Upsert RPC.
	AnalyticServiceUpsertProcedure = "/olympus.analytic.v1.AnalyticService/Upsert"
	// AnalyticServiceQueryDataProcedure is the fully-qualified name of the AnalyticService's QueryData
	// RPC.
	AnalyticServiceQueryDataProcedure = "/olympus.analytic.v1.AnalyticService/QueryData"
	// AnalyticServiceQueryBigQueryProcedure is the fully-qualified name of the AnalyticService's
	// QueryBigQuery RPC.
	AnalyticServiceQueryBigQueryProcedure = "/olympus.analytic.v1.AnalyticService/QueryBigQuery"
	// AnalyticServiceExecuteSQLProcedure is the fully-qualified name of the AnalyticService's
	// ExecuteSQL RPC.
	AnalyticServiceExecuteSQLProcedure = "/olympus.analytic.v1.AnalyticService/ExecuteSQL"
	// AnalyticServiceSetCacheProcedure is the fully-qualified name of the AnalyticService's SetCache
	// RPC.
	AnalyticServiceSetCacheProcedure = "/olympus.analytic.v1.AnalyticService/SetCache"
	// AnalyticServiceGetCacheProcedure is the fully-qualified name of the AnalyticService's GetCache
	// RPC.
	AnalyticServiceGetCacheProcedure = "/olympus.analytic.v1.AnalyticService/GetCache"
	// AnalyticServicePredictProcedure is the fully-qualified name of the AnalyticService's Predict RPC.
	AnalyticServicePredictProcedure = "/olympus.analytic.v1.AnalyticService/Predict"
	// AnalyticServiceEmbedProcedure is the fully-qualified name of the AnalyticService's Embed RPC.
	AnalyticServiceEmbedProcedure = "/olympus.analytic.v1.AnalyticService/Embed"
	// AnalyticServiceSpannerQueryProcedure is the fully-qualified name of the AnalyticService's
	// SpannerQuery RPC.
	AnalyticServiceSpannerQueryProcedure = "/olympus.analytic.v1.AnalyticService/SpannerQuery"
)

// AnalyticServiceClient is a client for the olympus.analytic.v1.AnalyticService service.
type AnalyticServiceClient interface {
	// --- Cloud Storage (GCS) ---
	GetDownloadURL(context.Context, *connect.Request[v1.GCSRequest]) (*connect.Response[v1.GCSResponse], error)
	UploadObject(context.Context, *connect.Request[v1.UploadRequest]) (*connect.Response[v1.UploadResponse], error)
	// --- NoSQL / Firestore ---
	Upsert(context.Context, *connect.Request[v1.UpsertRequest]) (*connect.Response[v1.StatusResponse], error)
	QueryData(context.Context, *connect.Request[v1.QueryRequest]) (*connect.Response[v1.JSONResponse], error)
	// --- Analytics / BigQuery ---
	QueryBigQuery(context.Context, *connect.Request[v1.BigQueryRequest]) (*connect.Response[v1.JSONResponse], error)
	// --- Relational / Cloud SQL ---
	ExecuteSQL(context.Context, *connect.Request[v1.SQLRequest]) (*connect.Response[v1.JSONResponse], error)
	// --- Cache / MemoryStore ---
	SetCache(context.Context, *connect.Request[v1.CacheRequest]) (*connect.Response[v1.StatusResponse], error)
	GetCache(context.Context, *connect.Request[v1.CacheRequest]) (*connect.Response[v1.JSONResponse], error)
	// --- AI / Vertex / Ollama ---
	Predict(context.Context, *connect.Request[v1.PredictRequest]) (*connect.Response[v1.PredictResponse], error)
	Embed(context.Context, *connect.Request[v1.EmbedRequest]) (*connect.Response[v1.EmbedResponse], error)
	// --- Cloud Spanner (Expansion) ---
	SpannerQuery(context.Context, *connect.Request[v1.SpannerRequest]) (*connect.Response[v1.JSONResponse], error)
}

// NewAnalyticServiceClient constructs a client for the olympus.analytic.v1.AnalyticService service.
// By default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped
// responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewAnalyticServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) AnalyticServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	analyticServiceMethods := v1.File_olympus_analytic_v1_analytic_proto.Services().ByName("AnalyticService").Methods()
	return &analyticServiceClient{
		getDownloadURL: connect.NewClient[v1.GCSRequest, v1.GCSResponse](
			httpClient,
			baseURL+AnalyticServiceGetDownloadURLProcedure,
			connect.WithSchema(analyticServiceMethods.ByName("GetDownloadURL")),
			connect.WithClientOptions(opts...),
		),
		uploadObject: connect.NewClient[v1.UploadRequest, v1.UploadResponse](
			httpClient,
			baseURL+AnalyticServiceUploadObjectProcedure,
			connect.WithSchema(analyticServiceMethods.ByName("UploadObject")),
			connect.WithClientOptions(opts...),
		),
		upsert: connect.NewClient[v1.UpsertRequest, v1.StatusResponse](
			httpClient,
			baseURL+AnalyticServiceUpsertProcedure,
			connect.WithSchema(analyticServiceMethods.ByName("Upsert")),
			connect.WithClientOptions(opts...),
		),
		queryData: connect.NewClient[v1.QueryRequest, v1.JSONResponse](
			httpClient,
			baseURL+AnalyticServiceQueryDataProcedure,
			connect.WithSchema(analyticServiceMethods.ByName("QueryData")),
			connect.WithClientOptions(opts...),
		),
		queryBigQuery: connect.NewClient[v1.BigQueryRequest, v1.JSONResponse](
			httpClient,
			baseURL+AnalyticServiceQueryBigQueryProcedure,
			connect.WithSchema(analyticServiceMethods.ByName("QueryBigQuery")),
			connect.WithClientOptions(opts...),
		),
		executeSQL: connect.NewClient[v1.SQLRequest, v1.JSONResponse](
			httpClient,
			baseURL+AnalyticServiceExecuteSQLProcedure,
			connect.WithSchema(analyticServiceMethods.ByName("ExecuteSQL")),
			connect.WithClientOptions(opts...),
		),
		setCache: connect.NewClient[v1.CacheRequest, v1.StatusResponse](
			httpClient,
			baseURL+AnalyticServiceSetCacheProcedure,
			connect.WithSchema(analyticServiceMethods.ByName("SetCache")),
			connect.WithClientOptions(opts...),
		),
		getCache: connect.NewClient[v1.CacheRequest, v1.JSONResponse](
			httpClient,
			baseURL+AnalyticServiceGetCacheProcedure,
			connect.WithSchema(analyticServiceMethods.ByName("GetCache")),
			connect.WithClientOptions(opts...),
		),
		predict: connect.NewClient[v1.PredictRequest, v1.PredictResponse](
			httpClient,
			baseURL+AnalyticServicePredictProcedure,
			connect.WithSchema(analyticServiceMethods.ByName("Predict")),
			connect.WithClientOptions(opts...),
		),
		embed: connect.NewClient[v1.EmbedRequest, v1.EmbedResponse](
			httpClient,
			baseURL+AnalyticServiceEmbedProcedure,
			connect.WithSchema(analyticServiceMethods.ByName("Embed")),
			connect.WithClientOptions(opts...),
		),
		spannerQuery: connect.NewClient[v1.SpannerRequest, v1.JSONResponse](
			httpClient,
			baseURL+AnalyticServiceSpannerQueryProcedure,
			connect.WithSchema(analyticServiceMethods.ByName("SpannerQuery")),
			connect.WithClientOptions(opts...),
		),
	}
}

// analyticServiceClient implements AnalyticServiceClient.
type analyticServiceClient struct {
	getDownloadURL *connect.Client[v1.GCSRequest, v1.GCSResponse]
	uploadObject   *connect.Client[v1.UploadRequest, v1.UploadResponse]
	upsert         *connect.Client[v1.UpsertRequest, v1.StatusResponse]
	queryData      *connect.Client[v1.QueryRequest, v1.JSONResponse]
	queryBigQuery  *connect.Client[v1.BigQueryRequest, v1.JSONResponse]
	executeSQL     *connect.Client[v1.SQLRequest, v1.JSONResponse]
	setCache       *connect.Client[v1.CacheRequest, v1.StatusResponse]
	getCache       *connect.Client[v1.CacheRequest, v1.JSONResponse]
	predict        *connect.Client[v1.PredictRequest, v1.PredictResponse]
	embed          *connect.Client[v1.EmbedRequest, v1.EmbedResponse]
	spannerQuery   *connect.Client[v1.SpannerRequest, v1.JSONResponse]
}

// GetDownloadURL calls olympus.analytic.v1.AnalyticService.GetDownloadURL.
func (c *analyticServiceClient) GetDownloadURL(ctx context.Context, req *connect.Request[v1.GCSRequest]) (*connect.Response[v1.GCSResponse], error) {
	return c.getDownloadURL.CallUnary(ctx, req)
}

// UploadObject calls olympus.analytic.v1.AnalyticService.UploadObject.
func (c *analyticServiceClient) UploadObject(ctx context.Context, req *connect.Request[v1.UploadRequest]) (*connect.Response[v1.UploadResponse], error) {
	return c.uploadObject.CallUnary(ctx, req)
}

// Upsert calls olympus.analytic.v1.AnalyticService.Upsert.
func (c *analyticServiceClient) Upsert(ctx context.Context, req *connect.Request[v1.UpsertRequest]) (*connect.Response[v1.StatusResponse], error) {
	return c.upsert.CallUnary(ctx, req)
}

// QueryData calls olympus.analytic.v1.AnalyticService.QueryData.
func (c *analyticServiceClient) QueryData(ctx context.Context, req *connect.Request[v1.QueryRequest]) (*connect.Response[v1.JSONResponse], error) {
	return c.queryData.CallUnary(ctx, req)
}

// QueryBigQuery calls olympus.analytic.v1.AnalyticService.QueryBigQuery.
func (c *analyticServiceClient) QueryBigQuery(ctx context.Context, req *connect.Request[v1.BigQueryRequest]) (*connect.Response[v1.JSONResponse], error) {
	return c.queryBigQuery.CallUnary(ctx, req)
}

// ExecuteSQL calls olympus.analytic.v1.AnalyticService.ExecuteSQL.
func (c *analyticServiceClient) ExecuteSQL(ctx context.Context, req *connect.Request[v1.SQLRequest]) (*connect.Response[v1.JSONResponse], error) {
	return c.executeSQL.CallUnary(ctx, req)
}

// SetCache calls olympus.analytic.v1.AnalyticService.SetCache.
func (c *analyticServiceClient) SetCache(ctx context.Context, req *connect.Request[v1.CacheRequest]) (*connect.Response[v1.StatusResponse], error) {
	return c.setCache.CallUnary(ctx, req)
}

// GetCache calls olympus.analytic.v1.AnalyticService.GetCache.
func (c *analyticServiceClient) GetCache(ctx context.Context, req *connect.Request[v1.CacheRequest]) (*connect.Response[v1.JSONResponse], error) {
	return c.getCache.CallUnary(ctx, req)
}

// Predict calls olympus.analytic.v1.AnalyticService.Predict.
func (c *analyticServiceClient) Predict(ctx context.Context, req *connect.Request[v1.PredictRequest]) (*connect.Response[v1.PredictResponse], error) {
	return c.predict.CallUnary(ctx, req)
}

// Embed calls olympus.analytic.v1.AnalyticService.Embed.
func (c *analyticServiceClient) Embed(ctx context.Context, req *connect.Request[v1.EmbedRequest]) (*connect.Response[v1.EmbedResponse], error) {
	return c.embed.CallUnary(ctx, req)
}

// SpannerQuery calls olympus.analytic.v1.AnalyticService.SpannerQuery.
func (c *analyticServiceClient) SpannerQuery(ctx context.Context, req *connect.Request[v1.SpannerRequest]) (*connect.Response[v1.JSONResponse], error) {
	return c.spannerQuery.CallUnary(ctx, req)
}

// AnalyticServiceHandler is an implementation of the olympus.analytic.v1.AnalyticService service.
type AnalyticServiceHandler interface {
	// --- Cloud Storage (GCS) ---
	GetDownloadURL(context.Context, *connect.Request[v1.GCSRequest]) (*connect.Response[v1.GCSResponse], error)
	UploadObject(context.Context, *connect.Request[v1.UploadRequest]) (*connect.Response[v1.UploadResponse], error)
	// --- NoSQL / Firestore ---
	Upsert(context.Context, *connect.Request[v1.UpsertRequest]) (*connect.Response[v1.StatusResponse], error)
	QueryData(context.Context, *connect.Request[v1.QueryRequest]) (*connect.Response[v1.JSONResponse], error)
	// --- Analytics / BigQuery ---
	QueryBigQuery(context.Context, *connect.Request[v1.BigQueryRequest]) (*connect.Response[v1.JSONResponse], error)
	// --- Relational / Cloud SQL ---
	ExecuteSQL(context.Context, *connect.Request[v1.SQLRequest]) (*connect.Response[v1.JSONResponse], error)
	// --- Cache / MemoryStore ---
	SetCache(context.Context, *connect.Request[v1.CacheRequest]) (*connect.Response[v1.StatusResponse], error)
	GetCache(context.Context, *connect.Request[v1.CacheRequest]) (*connect.Response[v1.JSONResponse], error)
	// --- AI / Vertex / Ollama ---
	Predict(context.Context, *connect.Request[v1.PredictRequest]) (*connect.Response[v1.PredictResponse], error)
	Embed(context.Context, *connect.Request[v1.EmbedRequest]) (*connect.Response[v1.EmbedResponse], error)
	// --- Cloud Spanner (Expansion) ---
	SpannerQuery(context.Context, *connect.Request[v1.SpannerRequest]) (*connect.Response[v1.JSONResponse], error)
}

// NewAnalyticServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewAnalyticServiceHandler(svc AnalyticServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	analyticServiceMethods := v1.File_olympus_analytic_v1_analytic_proto.Services().ByName("AnalyticService").Methods()
	analyticServiceGetDownloadURLHandler := connect.NewUnaryHandler(
		AnalyticServiceGetDownloadURLProcedure,
		svc.GetDownloadURL,
		connect.WithSchema(analyticServiceMethods.ByName("GetDownloadURL")),
		connect.WithHandlerOptions(opts...),
	)
	analyticServiceUploadObjectHandler := connect.NewUnaryHandler(
		AnalyticServiceUploadObjectProcedure,
		svc.UploadObject,
		connect.WithSchema(analyticServiceMethods.ByName("UploadObject")),
		connect.WithHandlerOptions(opts...),
	)
	analyticServiceUpsertHandler := connect.NewUnaryHandler(
		AnalyticServiceUpsertProcedure,
		svc.Upsert,
		connect.WithSchema(analyticServiceMethods.ByName("Upsert")),
		connect.WithHandlerOptions(opts...),
	)
	analyticServiceQueryDataHandler := connect.NewUnaryHandler(
		AnalyticServiceQueryDataProcedure,
		svc.QueryData,
		connect.WithSchema(analyticServiceMethods.ByName("QueryData")),
		connect.WithHandlerOptions(opts...),
	)
	analyticServiceQueryBigQueryHandler := connect.NewUnaryHandler(
		AnalyticServiceQueryBigQueryProcedure,
		svc.QueryBigQuery,
		connect.WithSchema(analyticServiceMethods.ByName("QueryBigQuery")),
		connect.WithHandlerOptions(opts...),
	)
	analyticServiceExecuteSQLHandler := connect.NewUnaryHandler(
		AnalyticServiceExecuteSQLProcedure,
		svc.ExecuteSQL,
		connect.WithSchema(analyticServiceMethods.ByName("ExecuteSQL")),
		connect.WithHandlerOptions(opts...),
	)
	analyticServiceSetCacheHandler := connect.NewUnaryHandler(
		AnalyticServiceSetCacheProcedure,
		svc.SetCache,
		connect.WithSchema(analyticServiceMethods.ByName("SetCache")),
		connect.WithHandlerOptions(opts...),
	)
	analyticServiceGetCacheHandler := connect.NewUnaryHandler(
		AnalyticServiceGetCacheProcedure,
		svc.GetCache,
		connect.WithSchema(analyticServiceMethods.ByName("GetCache")),
		connect.WithHandlerOptions(opts...),
	)
	analyticServicePredictHandler := connect.NewUnaryHandler(
		AnalyticServicePredictProcedure,
		svc.Predict,
		connect.WithSchema(analyticServiceMethods.ByName("Predict")),
		connect.WithHandlerOptions(opts...),
	)
	analyticServiceEmbedHandler := connect.NewUnaryHandler(
		AnalyticServiceEmbedProcedure,
		svc.Embed,
		connect.WithSchema(analyticServiceMethods.ByName("Embed")),
		connect.WithHandlerOptions(opts...),
	)
	analyticServiceSpannerQueryHandler := connect.NewUnaryHandler(
		AnalyticServiceSpannerQueryProcedure,
		svc.SpannerQuery,
		connect.WithSchema(analyticServiceMethods.ByName("SpannerQuery")),
		connect.WithHandlerOptions(opts...),
	)
	return "/olympus.analytic.v1.AnalyticService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case AnalyticServiceGetDownloadURLProcedure:
			analyticServiceGetDownloadURLHandler.ServeHTTP(w, r)
		case AnalyticServiceUploadObjectProcedure:
			analyticServiceUploadObjectHandler.ServeHTTP(w, r)
		case AnalyticServiceUpsertProcedure:
			analyticServiceUpsertHandler.ServeHTTP(w, r)
		case AnalyticServiceQueryDataProcedure:
			analyticServiceQueryDataHandler.ServeHTTP(w, r)
		case AnalyticServiceQueryBigQueryProcedure:
			analyticServiceQueryBigQueryHandler.ServeHTTP(w, r)
		case AnalyticServiceExecuteSQLProcedure:
			analyticServiceExecuteSQLHandler.ServeHTTP(w, r)
		case AnalyticServiceSetCacheProcedure:
			analyticServiceSetCacheHandler.ServeHTTP(w, r)
		case AnalyticServiceGetCacheProcedure:
			analyticServiceGetCacheHandler.ServeHTTP(w, r)
		case AnalyticServicePredictProcedure:
			analyticServicePredictHandler.ServeHTTP(w, r)
		case AnalyticServiceEmbedProcedure:
			analyticServiceEmbedHandler.ServeHTTP(w, r)
		case AnalyticServiceSpannerQueryProcedure:
			analyticServiceSpannerQueryHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedAnalyticServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedAnalyticServiceHandler struct{}

func (UnimplementedAnalyticServiceHandler) GetDownloadURL(context.Context, *connect.Request[v1.GCSRequest]) (*connect.Response[v1.GCSResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("olympus.analytic.v1.AnalyticService.GetDownloadURL is not implemented"))
}

func (UnimplementedAnalyticServiceHandler) UploadObject(context.Context, *connect.Request[v1.UploadRequest]) (*connect.Response[v1.UploadResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("olympus.analytic.v1.AnalyticService.UploadObject is not implemented"))
}

func (UnimplementedAnalyticServiceHandler) Upsert(context.Context, *connect.Request[v1.UpsertRequest]) (*connect.Response[v1.StatusResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("olympus.analytic.v1.AnalyticService.Upsert is not implemented"))
}

func (UnimplementedAnalyticServiceHandler) QueryData(context.Context, *connect.Request[v1.QueryRequest]) (*connect.Response[v1.JSONResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("olympus.analytic.v1.AnalyticService.QueryData is not implemented"))
}

func (UnimplementedAnalyticServiceHandler) QueryBigQuery(context.Context, *connect.Request[v1.BigQueryRequest]) (*connect.Response[v1.JSONResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("olympus.analytic.v1.AnalyticService.QueryBigQuery is not implemented"))
}

func (UnimplementedAnalyticServiceHandler) ExecuteSQL(context.Context, *connect.Request[v1.SQLRequest]) (*connect.Response[v1.JSONResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("olympus.analytic.v1.AnalyticService.ExecuteSQL is not implemented"))
}

func (UnimplementedAnalyticServiceHandler) SetCache(context.Context, *connect.Request[v1.CacheRequest]) (*connect.Response[v1.StatusResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("olympus.analytic.v1.AnalyticService.SetCache is not implemented"))
}

func (UnimplementedAnalyticServiceHandler) GetCache(context.Context, *connect.Request[v1.CacheRequest]) (*connect.Response[v1.JSONResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("olympus.analytic.v1.AnalyticService.GetCache is not implemented"))
}

func (UnimplementedAnalyticServiceHandler) Predict(context.Context, *connect.Request[v1.PredictRequest]) (*connect.Response[v1.PredictResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("olympus.analytic.v1.AnalyticService.Predict is not implemented"))
}

func (UnimplementedAnalyticServiceHandler) Embed(context.Context, *connect.Request[v1.EmbedRequest]) (*connect.Response[v1.EmbedResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("olympus.analytic.v1.AnalyticService.Embed is not implemented"))
}

func (UnimplementedAnalyticServiceHandler) SpannerQuery(context.Context, *connect.Request[v1.SpannerRequest]) (*connect.Response[v1.JSONResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("olympus.analytic.v1.AnalyticService.SpannerQuery is not implemented"))
}
