// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: olympus/analytic/v1/analytic.proto

package analyticv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Common Messages
type StatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_olympus_analytic_v1_analytic_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_olympus_analytic_v1_analytic_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_olympus_analytic_v1_analytic_proto_rawDescGZIP(), []int{0}
}

func (x *StatusResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type JSONResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Json          string                 `protobuf:"bytes,1,opt,name=json,proto3" json:"json,omitempty"`
	Count         int64                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JSONResponse) Reset() {
	*x = JSONResponse{}
	mi := &file_olympus_analytic_v1_analytic_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JSONResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JSONResponse) ProtoMessage() {}

func (x *JSONResponse) ProtoReflect() protoreflect.Message {
	mi := &file_olympus_analytic_v1_analytic_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JSONResponse.ProtoReflect.Descriptor instead.
func (*JSONResponse) Descriptor() ([]byte, []int) {
	return file_olympus_analytic_v1_analytic_proto_rawDescGZIP(), []int{1}
}

func (x *JSONResponse) GetJson() string {
	if x != nil {
		return x.Json
	}
	return ""
}

func (x *JSONResponse) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

// Storage Messages
type GCSRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bucket        string                 `protobuf:"bytes,1,opt,name=bucket,proto3" json:"bucket,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GCSRequest) Reset() {
	*x = GCSRequest{}
	mi := &file_olympus_analytic_v1_analytic_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GCSRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GCSRequest) ProtoMessage() {}

func (x *GCSRequest) ProtoReflect() protoreflect.Message {
	mi := &file_olympus_analytic_v1_analytic_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GCSRequest.ProtoReflect.Descriptor instead.
func (*GCSRequest) Descriptor() ([]byte, []int) {
	return file_olympus_analytic_v1_analytic_proto_rawDescGZIP(), []int{2}
}

func (x *GCSRequest) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *GCSRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GCSResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GCSResponse) Reset() {
	*x = GCSResponse{}
	mi := &file_olympus_analytic_v1_analytic_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GCSResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GCSResponse) ProtoMessage() {}

func (x *GCSResponse) ProtoReflect() protoreflect.Message {
	mi := &file_olympus_analytic_v1_analytic_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GCSResponse.ProtoReflect.Descriptor instead.
func (*GCSResponse) Descriptor() ([]byte, []int) {
	return file_olympus_analytic_v1_analytic_proto_rawDescGZIP(), []int{3}
}

func (x *GCSResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type UploadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bucket        string                 `protobuf:"bytes,1,opt,name=bucket,proto3" json:"bucket,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadRequest) Reset() {
	*x = UploadRequest{}
	mi := &file_olympus_analytic_v1_analytic_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadRequest) ProtoMessage() {}

func (x *UploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_olympus_analytic_v1_analytic_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadRequest.ProtoReflect.Descriptor instead.
func (*UploadRequest) Descriptor() ([]byte, []int) {
	return file_olympus_analytic_v1_analytic_proto_rawDescGZIP(), []int{4}
}

func (x *UploadRequest) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *UploadRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UploadRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type UploadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadResponse) Reset() {
	*x = UploadResponse{}
	mi := &file_olympus_analytic_v1_analytic_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadResponse) ProtoMessage() {}

func (x *UploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_olympus_analytic_v1_analytic_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadResponse.ProtoReflect.Descriptor instead.
func (*UploadResponse) Descriptor() ([]byte, []int) {
	return file_olympus_analytic_v1_analytic_proto_rawDescGZIP(), []int{5}
}

func (x *UploadResponse) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

// NoSQL Messages
type UpsertRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Collection    string                 `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"`
	DocId         string                 `protobuf:"bytes,2,opt,name=doc_id,json=docId,proto3" json:"doc_id,omitempty"`
	DataJson      string                 `protobuf:"bytes,3,opt,name=data_json,json=dataJson,proto3" json:"data_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertRequest) Reset() {
	*x = UpsertRequest{}
	mi := &file_olympus_analytic_v1_analytic_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertRequest) ProtoMessage() {}

func (x *UpsertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_olympus_analytic_v1_analytic_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertRequest.ProtoReflect.Descriptor instead.
func (*UpsertRequest) Descriptor() ([]byte, []int) {
	return file_olympus_analytic_v1_analytic_proto_rawDescGZIP(), []int{6}
}

func (x *UpsertRequest) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *UpsertRequest) GetDocId() string {
	if x != nil {
		return x.DocId
	}
	return ""
}

func (x *UpsertRequest) GetDataJson() string {
	if x != nil {
		return x.DataJson
	}
	return ""
}

type QueryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Collection    string                 `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"`
	Filter        string                 `protobuf:"bytes,2,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryRequest) Reset() {
	*x = QueryRequest{}
	mi := &file_olympus_analytic_v1_analytic_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRequest) ProtoMessage() {}

func (x *QueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_olympus_analytic_v1_analytic_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRequest.ProtoReflect.Descriptor instead.
func (*QueryRequest) Descriptor() ([]byte, []int) {
	return file_olympus_analytic_v1_analytic_proto_rawDescGZIP(), []int{7}
}

func (x *QueryRequest) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *QueryRequest) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

// BigQuery Messages
type BigQueryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BigQueryRequest) Reset() {
	*x = BigQueryRequest{}
	mi := &file_olympus_analytic_v1_analytic_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BigQueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BigQueryRequest) ProtoMessage() {}

func (x *BigQueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_olympus_analytic_v1_analytic_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BigQueryRequest.ProtoReflect.Descriptor instead.
func (*BigQueryRequest) Descriptor() ([]byte, []int) {
	return file_olympus_analytic_v1_analytic_proto_rawDescGZIP(), []int{8}
}

func (x *BigQueryRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

// SQL Messages
type SQLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,2,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	Query         string                 `protobuf:"bytes,3,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SQLRequest) Reset() {
	*x = SQLRequest{}
	mi := &file_olympus_analytic_v1_analytic_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SQLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SQLRequest) ProtoMessage() {}

func (x *SQLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_olympus_analytic_v1_analytic_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SQLRequest.ProtoReflect.Descriptor instead.
func (*SQLRequest) Descriptor() ([]byte, []int) {
	return file_olympus_analytic_v1_analytic_proto_rawDescGZIP(), []int{9}
}

func (x *SQLRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *SQLRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

// Cache Messages
type CacheRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CacheRequest) Reset() {
	*x = CacheRequest{}
	mi := &file_olympus_analytic_v1_analytic_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CacheRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheRequest) ProtoMessage() {}

func (x *CacheRequest) ProtoReflect() protoreflect.Message {
	mi := &file_olympus_analytic_v1_analytic_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheRequest.ProtoReflect.Descriptor instead.
func (*CacheRequest) Descriptor() ([]byte, []int) {
	return file_olympus_analytic_v1_analytic_proto_rawDescGZIP(), []int{10}
}

func (x *CacheRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *CacheRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// AI Messages
type PredictRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prompt        string                 `protobuf:"bytes,1,opt,name=prompt,proto3" json:"prompt,omitempty"`
	Model         string                 `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PredictRequest) Reset() {
	*x = PredictRequest{}
	mi := &file_olympus_analytic_v1_analytic_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PredictRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PredictRequest) ProtoMessage() {}

func (x *PredictRequest) ProtoReflect() protoreflect.Message {
	mi := &file_olympus_analytic_v1_analytic_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PredictRequest.ProtoReflect.Descriptor instead.
func (*PredictRequest) Descriptor() ([]byte, []int) {
	return file_olympus_analytic_v1_analytic_proto_rawDescGZIP(), []int{11}
}

func (x *PredictRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *PredictRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

type PredictResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prediction    string                 `protobuf:"bytes,1,opt,name=prediction,proto3" json:"prediction,omitempty"`
	UsageJson     string                 `protobuf:"bytes,2,opt,name=usage_json,json=usageJson,proto3" json:"usage_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PredictResponse) Reset() {
	*x = PredictResponse{}
	mi := &file_olympus_analytic_v1_analytic_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PredictResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PredictResponse) ProtoMessage() {}

func (x *PredictResponse) ProtoReflect() protoreflect.Message {
	mi := &file_olympus_analytic_v1_analytic_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PredictResponse.ProtoReflect.Descriptor instead.
func (*PredictResponse) Descriptor() ([]byte, []int) {
	return file_olympus_analytic_v1_analytic_proto_rawDescGZIP(), []int{12}
}

func (x *PredictResponse) GetPrediction() string {
	if x != nil {
		return x.Prediction
	}
	return ""
}

func (x *PredictResponse) GetUsageJson() string {
	if x != nil {
		return x.UsageJson
	}
	return ""
}

type EmbedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	Model         string                 `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmbedRequest) Reset() {
	*x = EmbedRequest{}
	mi := &file_olympus_analytic_v1_analytic_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbedRequest) ProtoMessage() {}

func (x *EmbedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_olympus_analytic_v1_analytic_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbedRequest.ProtoReflect.Descriptor instead.
func (*EmbedRequest) Descriptor() ([]byte, []int) {
	return file_olympus_analytic_v1_analytic_proto_rawDescGZIP(), []int{13}
}

func (x *EmbedRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *EmbedRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

type EmbedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []float32              `protobuf:"fixed32,1,rep,packed,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmbedResponse) Reset() {
	*x = EmbedResponse{}
	mi := &file_olympus_analytic_v1_analytic_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbedResponse) ProtoMessage() {}

func (x *EmbedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_olympus_analytic_v1_analytic_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbedResponse.ProtoReflect.Descriptor instead.
func (*EmbedResponse) Descriptor() ([]byte, []int) {
	return file_olympus_analytic_v1_analytic_proto_rawDescGZIP(), []int{14}
}

func (x *EmbedResponse) GetValues() []float32 {
	if x != nil {
		return x.Values
	}
	return nil
}

// Spanner Messages
type SpannerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Database      string                 `protobuf:"bytes,1,opt,name=database,proto3" json:"database,omitempty"`
	Query         string                 `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpannerRequest) Reset() {
	*x = SpannerRequest{}
	mi := &file_olympus_analytic_v1_analytic_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpannerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpannerRequest) ProtoMessage() {}

func (x *SpannerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_olympus_analytic_v1_analytic_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpannerRequest.ProtoReflect.Descriptor instead.
func (*SpannerRequest) Descriptor() ([]byte, []int) {
	return file_olympus_analytic_v1_analytic_proto_rawDescGZIP(), []int{15}
}

func (x *SpannerRequest) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

func (x *SpannerRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

var File_olympus_analytic_v1_analytic_proto protoreflect.FileDescriptor

const file_olympus_analytic_v1_analytic_proto_rawDesc = "" +
	"\n" +
	"\"olympus/analytic/v1/analytic.proto\x12\x13olympus.analytic.v1\"*\n" +
	"\x0eStatusResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"8\n" +
	"\fJSONResponse\x12\x12\n" +
	"\x04json\x18\x01 \x01(\tR\x04json\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x03R\x05count\"8\n" +
	"\n" +
	"GCSRequest\x12\x16\n" +
	"\x06bucket\x18\x01 \x01(\tR\x06bucket\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\x1f\n" +
	"\vGCSResponse\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"O\n" +
	"\rUploadRequest\x12\x16\n" +
	"\x06bucket\x18\x01 \x01(\tR\x06bucket\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\"$\n" +
	"\x0eUploadResponse\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"c\n" +
	"\rUpsertRequest\x12\x1e\n" +
	"\n" +
	"collection\x18\x01 \x01(\tR\n" +
	"collection\x12\x15\n" +
	"\x06doc_id\x18\x02 \x01(\tR\x05docId\x12\x1b\n" +
	"\tdata_json\x18\x03 \x01(\tR\bdataJson\"F\n" +
	"\fQueryRequest\x12\x1e\n" +
	"\n" +
	"collection\x18\x01 \x01(\tR\n" +
	"collection\x12\x16\n" +
	"\x06filter\x18\x02 \x01(\tR\x06filter\"'\n" +
	"\x0fBigQueryRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\"C\n" +
	"\n" +
	"SQLRequest\x12\x1f\n" +
	"\vinstance_id\x18\x02 \x01(\tR\n" +
	"instanceId\x12\x14\n" +
	"\x05query\x18\x03 \x01(\tR\x05query\"6\n" +
	"\fCacheRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\">\n" +
	"\x0ePredictRequest\x12\x16\n" +
	"\x06prompt\x18\x01 \x01(\tR\x06prompt\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\"P\n" +
	"\x0fPredictResponse\x12\x1e\n" +
	"\n" +
	"prediction\x18\x01 \x01(\tR\n" +
	"prediction\x12\x1d\n" +
	"\n" +
	"usage_json\x18\x02 \x01(\tR\tusageJson\">\n" +
	"\fEmbedRequest\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\"'\n" +
	"\rEmbedResponse\x12\x16\n" +
	"\x06values\x18\x01 \x03(\x02R\x06values\"B\n" +
	"\x0eSpannerRequest\x12\x1a\n" +
	"\bdatabase\x18\x01 \x01(\tR\bdatabase\x12\x14\n" +
	"\x05query\x18\x02 \x01(\tR\x05query2\xb5\a\n" +
	"\x0fAnalyticService\x12S\n" +
	"\x0eGetDownloadURL\x12\x1f.olympus.analytic.v1.GCSRequest\x1a .olympus.analytic.v1.GCSResponse\x12W\n" +
	"\fUploadObject\x12\".olympus.analytic.v1.UploadRequest\x1a#.olympus.analytic.v1.UploadResponse\x12Q\n" +
	"\x06Upsert\x12\".olympus.analytic.v1.UpsertRequest\x1a#.olympus.analytic.v1.StatusResponse\x12Q\n" +
	"\tQueryData\x12!.olympus.analytic.v1.QueryRequest\x1a!.olympus.analytic.v1.JSONResponse\x12X\n" +
	"\rQueryBigQuery\x12$.olympus.analytic.v1.BigQueryRequest\x1a!.olympus.analytic.v1.JSONResponse\x12P\n" +
	"\n" +
	"ExecuteSQL\x12\x1f.olympus.analytic.v1.SQLRequest\x1a!.olympus.analytic.v1.JSONResponse\x12R\n" +
	"\bSetCache\x12!.olympus.analytic.v1.CacheRequest\x1a#.olympus.analytic.v1.StatusResponse\x12P\n" +
	"\bGetCache\x12!.olympus.analytic.v1.CacheRequest\x1a!.olympus.analytic.v1.JSONResponse\x12T\n" +
	"\aPredict\x12#.olympus.analytic.v1.PredictRequest\x1a$.olympus.analytic.v1.PredictResponse\x12N\n" +
	"\x05Embed\x12!.olympus.analytic.v1.EmbedRequest\x1a\".olympus.analytic.v1.EmbedResponse\x12V\n" +
	"\fSpannerQuery\x12#.olympus.analytic.v1.SpannerRequest\x1a!.olympus.analytic.v1.JSONResponseBjZhOlympusGCP-Data-AI/40000-Communication-Contracts/430-Protocol-Definitions/000-gen/analytic/v1;analyticv1b\x06proto3"

var (
	file_olympus_analytic_v1_analytic_proto_rawDescOnce sync.Once
	file_olympus_analytic_v1_analytic_proto_rawDescData []byte
)

func file_olympus_analytic_v1_analytic_proto_rawDescGZIP() []byte {
	file_olympus_analytic_v1_analytic_proto_rawDescOnce.Do(func() {
		file_olympus_analytic_v1_analytic_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_olympus_analytic_v1_analytic_proto_rawDesc), len(file_olympus_analytic_v1_analytic_proto_rawDesc)))
	})
	return file_olympus_analytic_v1_analytic_proto_rawDescData
}

var file_olympus_analytic_v1_analytic_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_olympus_analytic_v1_analytic_proto_goTypes = []any{
	(*StatusResponse)(nil),  // 0: olympus.analytic.v1.StatusResponse
	(*JSONResponse)(nil),    // 1: olympus.analytic.v1.JSONResponse
	(*GCSRequest)(nil),      // 2: olympus.analytic.v1.GCSRequest
	(*GCSResponse)(nil),     // 3: olympus.analytic.v1.GCSResponse
	(*UploadRequest)(nil),   // 4: olympus.analytic.v1.UploadRequest
	(*UploadResponse)(nil),  // 5: olympus.analytic.v1.UploadResponse
	(*UpsertRequest)(nil),   // 6: olympus.analytic.v1.UpsertRequest
	(*QueryRequest)(nil),    // 7: olympus.analytic.v1.QueryRequest
	(*BigQueryRequest)(nil), // 8: olympus.analytic.v1.BigQueryRequest
	(*SQLRequest)(nil),      // 9: olympus.analytic.v1.SQLRequest
	(*CacheRequest)(nil),    // 10: olympus.analytic.v1.CacheRequest
	(*PredictRequest)(nil),  // 11: olympus.analytic.v1.PredictRequest
	(*PredictResponse)(nil), // 12: olympus.analytic.v1.PredictResponse
	(*EmbedRequest)(nil),    // 13: olympus.analytic.v1.EmbedRequest
	(*EmbedResponse)(nil),   // 14: olympus.analytic.v1.EmbedResponse
	(*SpannerRequest)(nil),  // 15: olympus.analytic.v1.SpannerRequest
}
var file_olympus_analytic_v1_analytic_proto_depIdxs = []int32{
	2,  // 0: olympus.analytic.v1.AnalyticService.GetDownloadURL:input_type -> olympus.analytic.v1.GCSRequest
	4,  // 1: olympus.analytic.v1.AnalyticService.UploadObject:input_type -> olympus.analytic.v1.UploadRequest
	6,  // 2: olympus.analytic.v1.AnalyticService.Upsert:input_type -> olympus.analytic.v1.UpsertRequest
	7,  // 3: olympus.analytic.v1.AnalyticService.QueryData:input_type -> olympus.analytic.v1.QueryRequest
	8,  // 4: olympus.analytic.v1.AnalyticService.QueryBigQuery:input_type -> olympus.analytic.v1.BigQueryRequest
	9,  // 5: olympus.analytic.v1.AnalyticService.ExecuteSQL:input_type -> olympus.analytic.v1.SQLRequest
	10, // 6: olympus.analytic.v1.AnalyticService.SetCache:input_type -> olympus.analytic.v1.CacheRequest
	10, // 7: olympus.analytic.v1.AnalyticService.GetCache:input_type -> olympus.analytic.v1.CacheRequest
	11, // 8: olympus.analytic.v1.AnalyticService.Predict:input_type -> olympus.analytic.v1.PredictRequest
	13, // 9: olympus.analytic.v1.AnalyticService.Embed:input_type -> olympus.analytic.v1.EmbedRequest
	15, // 10: olympus.analytic.v1.AnalyticService.SpannerQuery:input_type -> olympus.analytic.v1.SpannerRequest
	3,  // 11: olympus.analytic.v1.AnalyticService.GetDownloadURL:output_type -> olympus.analytic.v1.GCSResponse
	5,  // 12: olympus.analytic.v1.AnalyticService.UploadObject:output_type -> olympus.analytic.v1.UploadResponse
	0,  // 13: olympus.analytic.v1.AnalyticService.Upsert:output_type -> olympus.analytic.v1.StatusResponse
	1,  // 14: olympus.analytic.v1.AnalyticService.QueryData:output_type -> olympus.analytic.v1.JSONResponse
	1,  // 15: olympus.analytic.v1.AnalyticService.QueryBigQuery:output_type -> olympus.analytic.v1.JSONResponse
	1,  // 16: olympus.analytic.v1.AnalyticService.ExecuteSQL:output_type -> olympus.analytic.v1.JSONResponse
	0,  // 17: olympus.analytic.v1.AnalyticService.SetCache:output_type -> olympus.analytic.v1.StatusResponse
	1,  // 18: olympus.analytic.v1.AnalyticService.GetCache:output_type -> olympus.analytic.v1.JSONResponse
	12, // 19: olympus.analytic.v1.AnalyticService.Predict:output_type -> olympus.analytic.v1.PredictResponse
	14, // 20: olympus.analytic.v1.AnalyticService.Embed:output_type -> olympus.analytic.v1.EmbedResponse
	1,  // 21: olympus.analytic.v1.AnalyticService.SpannerQuery:output_type -> olympus.analytic.v1.JSONResponse
	11, // [11:22] is the sub-list for method output_type
	0,  // [0:11] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_olympus_analytic_v1_analytic_proto_init() }
func file_olympus_analytic_v1_analytic_proto_init() {
	if File_olympus_analytic_v1_analytic_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_olympus_analytic_v1_analytic_proto_rawDesc), len(file_olympus_analytic_v1_analytic_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_olympus_analytic_v1_analytic_proto_goTypes,
		DependencyIndexes: file_olympus_analytic_v1_analytic_proto_depIdxs,
		MessageInfos:      file_olympus_analytic_v1_analytic_proto_msgTypes,
	}.Build()
	File_olympus_analytic_v1_analytic_proto = out.File
	file_olympus_analytic_v1_analytic_proto_goTypes = nil
	file_olympus_analytic_v1_analytic_proto_depIdxs = nil
}
